### ISSUE TITLE
Toggles

### ISSUE THREAD

**Issue by Mouad-scriptz** [shlexware/Orion#11]
When its the toggle is on it will stay on even if you disable it please fix.

**Comment by Kxifed** [comment]
try adding getgenv

main:AddToggle({
    Name = "print hi",
    Default = false,
    Callback = function(Value)
        getgenv().namethinghere = Value
        while getgenv().namethinghere do
            task.wait()
            print("hi")
            end
    end
})

**Comment by Mouad-scriptz** [comment]
Thank you but i already figured it out also you can use "while namethinghere do"
