### ISSUE TITLE
OrionLib:Destroy() is not working

### ISSUE THREAD

**Issue by ReLoia** [shlexware/Orion#12]
Executing it gives `attempt to call a nil value` Error

Printing the library I get this:
![Result](https://i.imgur.com/pNfFj2Z.png)
No trace of `:Destroy()`

Is there any way to fix it myself or I need to wait for a fix?
Thanks in advance

**Comment by xcp9** [comment]
Rearrange the Local OrionLib on top of all your code. Btw what even is this?

**Comment by ReLoia** [comment]
I printed the lib's table elements to see if the `:Destroy()` function was there but it isn't there.
I don't think moving `local OrionLib` on top would change anything. 

The problem is that the `:Destroy()` function isn't there probably in one of the latest updates it got removed by mistake and we users can't do anything because it isn't open source.
