### ISSUE TITLE
How do I put buttons in a different section?

### ISSUE THREAD

**Issue by madvoids** [shlexware/Orion#28]
so i have 2 sections in a tab, but i want 2 buttons in those 2 sections. 1 button in the first section and 1 button on the second section

**Comment by DABIGAMER** [comment]
If you have 2 section do this to put button
{The section command line }
(Button 1 command)
{The section 2 command line}
(Button 2 command )
These are just example don't use those line in the hub

**Comment by shlexware** [comment]
Make Window, Make Tab, Make Section, Make Button, Make Section, Make Button

in that order
